image: docker:stable
stages:
  - build
  - test

build:
  stage: build
  services:
    - docker:dind
  script:
    - echo "starting docker build......."
    - ls
    - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
    - docker build -t cicd-test .
    - docker images
    - docker tag cicd-test shahedmehbub/cicd-test
    - docker push shahedmehbub/cicd-test

test:
  stage: test
  services:
    - docker:dind
  image: ictu/sshpass
  script:
    - sshpass -p hello123 ssh -o StrictHostKeyChecking=no cicduser@139.59.106.149 "touch cicdtest.txt"
