image: docker:stable
stages:
  - aws
  - build
  - test

# aws:
#   stage: aws
#   image:
#     name: amazon/aws-cli
#     entrypoint: [""]
#   services:
#     - docker:dind
#   script:
#     - aws s3 ls
#     - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 745137160548.dkr.ecr.us-west-2.amazonaws.com

aws:
  stage: aws
  image: bentolor/docker-dind-awscli
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - aws s3 ls
    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 745137160548.dkr.ecr.us-west-2.amazonaws.com

build:
  stage: build
  when: manual
  services:
    - docker:dind
  script:
    - echo "starting docker build......."
    - ls
    - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
    - docker build -t cicd-test .
    - docker images
    - docker tag cicd-test shahedmehbub/cicd-test
    - docker push shahedmehbub/cicd-test

test:
  stage: test
  when: manual
  services:
    - docker:dind
  image: ictu/sshpass
  script:
          - sshpass -p hello123 ssh -o StrictHostKeyChecking=no cicduser@139.59.106.149 "docker stop cicd-test && docker rm cicd-test && docker rmi shahedmehbub/cicd-test && docker run -d --name cicd-test -p 5000:5000 shahedmehbub/cicd-test"
